// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fvxhbjypaybgmqsfyfbb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ2eGhianlwYXliZ21xc2Z5ZmJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3NjQ0NDEsImV4cCI6MjA1OTM0MDQ0MX0.XgJqZ-36b_OtL5-FLwhH3TahmjOGIC5rh5WwU8HRdh8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);